Service config
ezpaarse-project/ezunpaywall pull request #122
Opened 2023-03-08 12:25 UTC by felixleo22

Feature: 

- At the start of each service, it display log the node config without secrets keys

2023-03-17 09:18 UTC, oxypomme requested changes

2023-03-17 09:18 UTC, oxypomme commented on src/apikey/app.js
> +  getConfig(true);
You may want to use env instead of forcing it

2023-03-17 09:18 UTC, oxypomme commented on src/enrich/app.js
> +  getConfig(true);
You may want to use env instead of forcing it

2023-03-17 09:18 UTC, oxypomme commented on src/health/app.js
> +  getConfig(true);
You may want to use env instead of forcing it

2023-03-17 09:18 UTC, oxypomme commented on src/mail/app.js
> +  getConfig(true);
You may want to use env instead of forcing it

2023-03-17 09:18 UTC, oxypomme commented on src/update/app.js
> +  getConfig(true);
You may want to use env instead of forcing it

2023-03-17 09:18 UTC, oxypomme commented on src/graphql/app.js
> +  getConfig(true);
You may want to use env instead of forcing it

2023-04-03 12:08 UTC, nojhamster approved these changes

2023-04-03 12:11 UTC, oxypomme approved these changes

2023-04-03 12:11 UTC, merged