feat: auth service
ezpaarse-project/ezunpaywall pull request #31
Opened 2021-11-02 13:11 UTC by felixleo22

2021-11-02 16:06 UTC, nojhamster commented on src/auth/routers/manage.js
> +  await redisClient.flushall();
```suggestion
  try {
    await redisClient.flushall();
  } catch (err) {
    return next(err);
  }
```

2021-11-02 16:06 UTC, nojhamster commented on src/auth/routers/manage.js
> +  await load();
```suggestion
  try {
    await load();
  } catch (err) {
    return next(err);
  }
```

2021-11-03 06:30 UTC, felixleo22 commented
You can merge, i have done all of your suggestion

2021-11-19 15:39 UTC, nojhamster requested changes

2021-11-19 15:39 UTC, nojhamster commented on src/apikey/lib/redis.js
> +  }
```suggestion
  const filename = process.env.NODE_ENV === 'production' ? 'apikey.json' : 'apikey-dev.json';
  apiKeys = await fs.readFile(path.resolve(__dirname, '..', filename), 'utf8');
```
Just another way to do the same thing.

2021-11-19 15:39 UTC, nojhamster commented on src/apikey/lib/redis.js
>    });
```suggestion
  await Promise.all(
    Object.entries(apiKeys).map(async ([keyId, keyValue]) => {
      try {
        await redisClient.set(keyId, `${JSON.stringify(keyValue)}`);
      } catch (err) {
        logger.error(`Cannot load ${keyId} with ${JSON.stringify(keyValue)} on redis`);
        logger.error(err);
      }
    })
  );
```
`forEach()` will not wait for the promises to be resolved, so if you want to be sure that the keys are loaded when the `load()` function resolves, you should use either `Promise.all` (to run them in parallel) or a `for loop` (to run them sequentially).

2021-11-19 15:39 UTC, nojhamster commented on src/apikey/middlewares/auth.js
> +  }
```suggestion
  if (apikey !== config.get('redis.password')) {
    return res.status(401).json({ message: 'Not authorized' });
  }
```
If `apikey` is not set, it won't match the password anyway. However you can also write `if (!apikey || apikey !== config.get('redis.password'))` to cover the case where `redis.password` is not set, without duplicating code.

2021-11-19 15:39 UTC, nojhamster commented on src/apikey/routers/manage.js
> +  }
Don't forget to handle promise rejections, as express does not handle promises.

2021-11-19 15:39 UTC, nojhamster commented on src/apikey/routers/manage.js
> +  });
Don't forget to handle promise rejections, as express does not handle promises.

2021-11-19 15:39 UTC, nojhamster commented on src/apikey/routers/manage.js
> +  let config = await redisClient.get(apikey);
Don't forget to handle promise rejections, as express does not handle promises.

2021-11-19 15:39 UTC, nojhamster commented on src/apikey/routers/manage.js
> +  let configApiKey = await redisClient.get(apikey);
Don't forget to handle promise rejections, as express does not handle promises.

2021-11-19 15:39 UTC, nojhamster commented on src/apikey/routers/manage.js
> +  });
Same as the `load()` function in `lib/redis.js`, you should either use `Promise.all()` or a `for loop` to be sure that the keys are actually loaded when the server responds.

2021-11-22 09:59 UTC, felixleo22 commented on src/apikey/lib/redis.js
> +  }
ok i follow that

2021-11-22 12:32 UTC, merged